
version: "3.8"
services:
  mongo:
    image: mongo:7
    container_name: dtm-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  redis:
    image: redis:7
    container_name: dtm-redis
    ports:
      - "6379:6379"
volumes:
  mongo_data:
